apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerized-neighborly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dockerized-neighborly
  template:
    metadata:
      labels:
        app: dockerized-neighborly
    spec:
      containers:
      - name: dockerized-neighborly
        image: neighborlycr.azurecr.io/my-func-app:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pyfunc-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: dockerized-neighborly